POST https://api.github.com/repos/WoutervanderLaan/AudioTour/actions/workflows/ai-agent.yml/dispatches HTTP/1.1
Accept:: application/vnd.github+json
Authorization: Bearer <GITHUB_TOKEN>

{
    "ref": "main",
    "inputs": {
        "trelloCardId": "1234567890",
        "title": "Test Title",
        "description": "This is a test description for the Trello card. "
    }
}